### ISSUE TITLE
Please add slash commands

### ISSUE THREAD

**Issue by Thundros** [pvalls/chat3D#1]
Hi! First off I'd like to say : EXCELLENT work on this project! Keep up the amazing work! <3 Secondly, could you please add administrators / global mods / mods / users & allow each of these their own slash commands in chat? Thanks!

**Comment by pvalls** [comment]
Thank you for your comment Thundros! <3.

Regarding your request unfortunately this repo represents a subject's assignment delivery and you must work with it as is. Therefore, it is not necessary to track it as the original "upstream" of your fork or perform pull requests from it.

Nevertheless, you can implement any change you would like to your forked copy, I will be happy to respond any inquiry and I will love to see how the project evolves. Thanks!
